name=NetronixSerdes
version=1.0.0
author=Michal Bazan
maintainer=Michal Bazan <michalbaz@poczta.onet.pl>
sentence=Lightweight Netronix protocol frame serializer/deserializer for embedded systems
paragraph=Implements a lightweight SERDES with CRC16 support and frame validation for Netronix protocol - could be used in any type of simple communication.
category=Communication
url=https://github.com/DevxMike/NetronixSerdes
architectures=*
includes=netronix_frame.h
